# Generated by Django 3.0.7 on 2021-06-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_tutorials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorials',
        ),
    ]
