# Generated by Django 3.0.7 on 2021-06-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_delete_tutorials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
